# .github/workflows/pr-test.yml
name: Test Rust Code on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build binaries
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose